name: Update submodule to latest

on:
    workflow_dispatch:

permissions:
  contents: write
  pull-requests: write  # Add permission to create PRs
  
jobs:
    reset-submodule:
        runs-on: ubuntu-latest
        env:
          BRANCH_NAME: update/theme-submodule-${{ github.run_number }}

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.CI_TOKEN }}
            submodules: recursive
            fetch-depth: 0

        - name: Debug info
          run: |
            echo "Repository: ${{ github.repository }}"
            git remote -v

        - name: Reset submodule
          env:
            GH_TOKEN: ${{ secrets.CI_TOKEN }}
          run: |
                # Configure git
                git config --global --add --bool push.autoSetupRemote true
                git config --global user.name 'github-actions[bot]'
                git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                
                # Create a new branch for the update
                git checkout -b ${{ env.BRANCH_NAME }}
                
                # Update submodule with explicit tracking
                cd themes/adritian-free-hugo-theme
                git fetch origin main
                git checkout main
                git reset --hard origin/main
                cd ../..
                
                # Force update submodule reference
                git submodule update --remote --force themes/adritian-free-hugo-theme
                
                # Show status for debugging
                echo "Git status:"
                git status
                
                # Commit and push changes
                git add themes/adritian-free-hugo-theme
                git commit -m "Update theme submodule to main" || echo "No changes to commit"
                git push origin ${{ env.BRANCH_NAME }}

        - name: Create Pull Request
          if: success()
          uses: peter-evans/create-pull-request@v6
          with:
            token: ${{ secrets.CI_TOKEN }}
            title: 'Update theme submodule to latest main'
            body: |
              This PR updates the theme submodule to the latest version from main branch.
              
              - Auto-generated by GitHub Actions
            branch: ${{ env.BRANCH_NAME }}
            base: main
            delete-branch: true
            labels: |
              automated pr
              theme update
            